version: '3.4'
services:
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: registrations
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  demo-ana:
    image: demo
    container_name: demo
    restart: on-failure
    build: .
    environment:
      TZ: GMT
    ports:
      - "9003:9003"
    networks:
      - backend
    depends_on:
      - mysqldb
    links:
      - "mysqldb:database"

volumes:
  db-data:

networks:
  backend: