server:
  port: 9003

spring:
  profiles:
    active: prod
    include: swagger
  datasource:
    url: jdbc:mysql://mysqldb:3306/registrations?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false


info:
  app:
    name: REGISTROS
    description: Aplicação para realizar novas registros
    version: 0.1.0


management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: health, info, env, flyway
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
    flyway:
      enabled: true