INSERT INTO status(name)
SELECT * FROM (SELECT 'REGISTRATION_PURCHASED') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM status WHERE name = 'REGISTRATION_PURCHASED'
) LIMIT 1;

INSERT INTO status(name)
SELECT * FROM (SELECT 'REGISTRATION_CANCELED') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM status WHERE name = 'REGISTRATION_CANCELED'
) LIMIT 1;

INSERT INTO status(name)
SELECT * FROM (SELECT 'REGISTRATION_RESTARTED') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM status WHERE name = 'REGISTRATION_RESTARTED'
) LIMIT 1;